# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Carlos Augusto Borges
# email: calimaborges@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Cientista da Computação. Estudou Computação na Universidade de Brasília.
    Atualmente desenvolve em Java (Web e Android) e Swift (iOS).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://carlosborg.es" # the base hostname & protocol for your site
twitter_username: calimaborges
github_username:  calimaborges

# Build settings
markdown: kramdown

# My settings
timezone: America/Sao_Paulo
permalink: /blog/:year/:month/:day/:title
